#!/usr/bin/env bash
task=$1 # ECQA / ESNLI
evaluate_on_task_model=$2
# 1: evaluate on rationales generated by a task model
# 0: evaluate on original human-annotated rationales from the dataset

OUT_DIR="./output/${task}"

if [ "$evaluate_on_task_model" -eq 1 ]; then
    echo "[INFO] Using task-model-generated rationales"
    python generate_data_for_ranking_metric.py \
        --task ${task} \
        --out_dir ${OUT_DIR} \
        --evaluate_on_task_model
else
   echo "[INFO] Using original human-annotated rationales"
   python generate_data_for_ranking_metric.py \
        --task ${task} \
        --out_dir ${OUT_DIR}
fi


